export type DurgethRawNameBase = {
  name: string;
  min: number;
  max: number;
  d: string;
  m: number;
  b: string;
};

export const DURGETH_NAMEBASES: DurgethRawNameBase[] = [
  {
    name: "ApisdrenBhutanAksumite",
    min: 4,
    max: 8,
    d: "",
    m: 0,
    b: "Apisdren,Khen,Zhen,Laeir,Khoten,Dehen,Dongom,Diren,Khoel,Moel,Monga,Chigom,Tamang,Phaen,Khongel,Karen,Suen,Ngaen,Nambren,Manen,Khyedel,Yagpang,Zhigang,Ngangel,Ditsang,Ngatshen,Yodeir,Nangweir,Sameir,Gien,Dangen,Kangom,Naeir,Neir,Yangmen,Kyen,Nesen,Yawen,Gebeir,Ngaom,Gyureir,Deben,Yaren,Chiren,Nagen,Koron,Chiru,Nangom,Khonam,Gangen,Yangeng,Logren,Jesen,Kolen,Dangpom,Legsang,Gaang,Gonmen,Yangyang,Thoang,Namyang,Changom,Jemen,Tsueir,Ngatsen,Baren,Nammen,Yangdang,Nyuren,Trangen,Droeir,Lungom,Nesang,Gegeir,Bareng,Denang,Cheyen,Kyidom,Yangden,Ogren,Laen,Kangseir,Bardom,Docha,Yinmen,Gyabeir,Zhanen,Thabang,Jaeir,Khoen,Taren,Khyeden,Khongeng,Zeir,Thobseir,Garen,Sobeir,Thubseir,Gaweir,Dusom,Sheseir,Langseir,Lomen,Thubpeng,Khongen,Thongeir,Nangseir,Yongeir,Koleir,Leom,Lamom,Sareng,Dodseir,Terngeir,Nyinom,Mangkang,Chenang,Lagom,Dzineir,Koreir",
  },
  {
    name: "ApiskeldSumerian",
    min: 4,
    max: 9,
    d: "",
    m: 0,
    b: "Apiskeld,Kiez,Laul,Suir,Bikul,Beul,Anakim,Naaul,Aniel,Munum,Dikul,Tamum,Phaaul,Anieum,Anakez,Abakez,Gaul,Enakez,Nulul,Zaiel,Dugakez,Lahul,Zanul,Minum,Mezieum,Naakum,Mezul,Tumakim,Gamir,Igigir,Subakir,Akul,Naakez,Zakim,Daakim,Kirim,Anzekim,Takim,Taakez,Enaul,Lugamir,Gakim,Nanimir,Kishakim,Anum,Barakim,Tukakim,Zakakim,Mekakim,Shakim,Anzeul,Anukim,Mashkim,Ginakim,Usikim,Tumir,Sagum,Dugakim,Laakim,Gaeshkim,Ushkim,Galum,Nulnamkim,Irigakim,Usiakez,Sagumir,Minukim,Enakim,Namkim,Anzeakez,Ginakez,Ginaul,Baramir,Imukim,Taeshkim,Gegumir,Shaakez,Sukim,Kimakim,Egirul,Haeul,Damir,Sharakez,Meeshkez,Zankim,Maakim,Dimumir,Tamir,Anezul,Zaaul,Anieshum,Mezakez,Kamir,Meshakim,Dumir,Zumir,Kigakim,Udum,Zumakez,Anieshkim,Igirir,Igirmir,Ginmir,Tumezkim,Akum,Gibulum,Gaeshumir,Sumir,Udul,Galakez,Galakim,Galul,Suul,Kiakez,Dashmir,Nimir,Sigum,Zinumir,Babbarum,Dumudum",
  },
  {
    name: "ApisveldirByzantineMughal",
    min: 4,
    max: 12,
    d: "",
    m: 0,
    b: "Apisveldir,Khel,Eisan,Prosir,Autoel,Ekeinal,Khanakim,Houtosan,Autouel,Autesel,Auteara,Heisel,Pasan,Ekeian,Autonel,Tian,Tisara,Emean,Hopotan,Oukhan,Sonel,Khubara,Tinesan,Allosel,Dyoan,Hemonel,Houtaan,Hemasan,Elabara,Einaiir,Phainiran,Noeisir,Touel,Kaian,Epian,Metaan,Enan,Allaan,Hypoan,Apoan,Etan,Melliran,Emonel,Ekhiran,Anoan,Exoan,Eian,Perian,Hotian,Eisoan,Mononan,Hyperan,Opisthel,Khrastiran,Protoel,Kalosan,Khreiaan,Pollakhisan,Hypselosan,Oudepotean,Boreasan,Hexesel,Arkhiran,Amphoteroian,Heosan,Potean,Kaiperan,Takheosan,Euthysan,Apienahir,Zephyrosel,Epeian,Kataan,Enoan,Alethosan,Prosan,Mesitoel,Etian,Opisthelan,Naian,Plerosir,Enamesan,Isosan,Eimian,Etanetan,Alloselan,Pantosan,Poiisir,Ekhisir,Autosel,Hosan,Syan,Autoian,Hemeisan,Legisir,Lambanisir,Ienaisir,Dynasthaisir,Phileisir,Khronosel,Eidenaisir,Etosel,Edynatoan,Autousan,Horeisir,Blepiran,Eltheisir,Khrastirir,Ergonel,Hodoel,Neosan,Boulisir,Didonisir,Hemerael,Pleistosan,Megalosan,Metaxyan,Megaloel,Kheirael,Toposel",
  },
  {
    name: "ArantzaKhoisanBasque",
    min: 4,
    max: 11,
    d: "",
    m: 0,
    b: "Arantza,Tzak,Batitza,Tzuri,Horitza,Haitza,Tzakori,Hauitza,Berekxo,Hauritz,Batqxan,Denakxo,Hantza,Eurenkxo,Zeritza,Noritza,Nitzak,Noizitza,Ezitza,Zurekxo,Onkxo,Batzuitza,Bestekxo,Bitzitza,Guretzak,Haueitza,Gutzak,Kxarituritz,Izananu,Dirudienitz,Uste,Rekxo,Etaitza,Gainekxo,Tzakxo,Anitza,Baitzak,Tikxo,Tikxori,Edokxo,Izangoitz,Nireitza,Litzakekxo,Horretzitza,Goraitza,Kanpoitza,Baldinitza,Buruzitza,Tzergatiitz,Barnekxo,Bakarritza,Gaineitzak,Ereitza,Atzeitza,Ondorenitz,Erabilianu,Lehenitza,Ongiitza,Areitza,Edozeitza,Beharitza,Askotzakxo,Altuitza,Inoizekxo,Ipartzak,Hurrengokxo,Hasianu,Biekxo,Arteitza,Inoizitza,Nahizitza,Lasteritza,Zuzenitza,Uzteanu,Haizeitza,Ezkerozitza,Aurkaitza,Bitartekxo,Egiakxo,Alderatzak,Erditzak,Oraindikxo,Gainekoitza,Atzekoitza,Baikxo,Beteanu,Artekoitza,Agianitz,Naitzak,Beharkoitz,Nahikoitza,Eginanu,Ukan,Berakxo,Bezalaitza,Zutzak,Eurekxo,Esan,Lortzanu,Zeineitza,Joan,Ahaltzak,Gustatu,Denboritza,Beratzak,Jakinanu,Hartuanu,Urteitza,Ahaltzakxo,Eurei,Ikusianu,Begiratuanu,Etorrianu,Lanitza,Bideitza,Berritza,Nahi,Emananu,Egunaitza,Gehienitza",
  },
  {
    name: "AshirumIcelandic",
    min: 4,
    max: 9,
    d: "",
    m: 0,
    b: "Ashirum,Icelandic,Einn,Essi,Hvat,Hverr,Varr,Vera,Ykkja,Hyggja,Eigi,Viat,Einungis,Eptir,Jafnvel,Essir,Braum,Sian,Gegn,Mean,Yfir,Aftan,Meal,Kannski,Skulu,Annahvort,Annars,Alveg,Gera,Hafa,Segja,Smia,Mega,Lika,Vita,Taka,Lita,Koma,Nota,Vinna,Vilja,Gefa,Halda,Snua,Ganga,Hefja,Opna,Hira,Finna,Tala,Hlaupa,Fara,Fylla,Gerast,Muna,Heyra,Hreyfa,Falla,Ferast,Syngja,Hlusta,Draga,Fylgja,Birtast,Jona,Stjorna,Eftir,Grata,Keyra,Leia,Standa,Innihalda,Kenna,Framleia,Akvea,Sanna,Dvelja,Vinga,Profa,Hlja,Undra,Kanna,Mota,Hita,Mala,Dansa,Breyta,Setjast,Veia,Telja,Takna,Sitja,Trua,Gripa,Oska,Sofa,Klifra,Fljuga,Geyma,Skera,Heimskja,Hoppa,Ljuka,Vona,Vaxa,Leysa,Elda,Brenna,Lysa,Afrita,Rulla,Berjast,Berja,Brjota,Drepa,Hann,Minn,Folk,Sumir,Mikill",
  },
  {
    name: "AshveldSwahiliQuechua",
    min: 4,
    max: 11,
    d: "",
    m: 0,
    b: "Ashveld,Moja,Kitu,Kile,Hiki,Yake,Yeye,Kimoja,Yote,Kule,Nini,Nani,Mimi,Lini,Hapana,Yako,Nzuri,Baadhi,Yetu,Hizi,Sisi,Kuwa,Kuonekana,Yachay,Pamoja,Katika,Lakini,Kutoka,Ataqa,Yangu,Ingekuwa,Hivyo,Kama,Kuhusu,Sababu,Ndani,Nyuma,Baada,Kutumia,Kwanza,Vizuri,Hata,Yoyote,Haja,Mara,Nyingi,Kamwe,Kaskazini,Ijayo,Kuanza,Alipata,Wote,Wawili,Hadi,Wakati,Wowote,Ingawa,Hivi,Karibuni,Kuacha,Upepo,Tangu,Dhidi,Kweli,Kuelekea,Katikati,Bado,Ndiyo,Kujaza,Miongoni,Labda,Niko,Itabidi,Kingine,Kabisa,Kufanya,Wewe,Kusema,Kupata,Ambayo,Kwenda,Kutengeneza,Kuweza,Kupenda,Kujua,Kuchukua,Mwaka,Angeweza,Kuona,Nyingine,Kuja,Kutazama,Kazi,Njia,Mpya,Kutaka,Kutoa,Siku,Zaidi,Hatun,Kati,Kubwa,Mkono,Mahali,Kushikilia,Kugeuza,Chache,Kufungua,Nyeupe,Watoto,Kutembea,Mfano,Urahisi,Karatasi,Kikundi,Daima,Muziki,Wale,Alama,Kitabu",
  },
  {
    name: "BovariScythian",
    min: 4,
    max: 8,
    d: "",
    m: 0,
    b: "Bovari,Scythian,Tara,Aita,Khavan,Ahma,Ahme,Asti,Avat,Vispat,Mananh,Noit,Upairi,Haca,Vaso,Pati,Hakat,Antar,Yezi,Paiti,Yavat,Aevo,Pasca,Aitaon,Zuta,Hacaet,Antarat,Havo,Pascat,Antara,Matha,Hishta,Anya,Mazant,Darat,Mrut,Alda,Karsh,Tavan,Suyun,Vida,Vaina,Spas,Karez,Kama,Varsh,Shyav,Fradata,Vispa,Vivar,Uruvar,Hish,Mruta,Zhugu,Shyavat,Bava,Guzar,Rasa,Srav,Zhyl,Pata,Sraota,Tart,Vispar,Banda,Xshay,Xshatra,Spasat,Griv,Fradat,Vardh,Varat,Areta,Aojah,Turt,Khuld,Aiwyn,Tapay,Rang,Vispata,Nist,Shkar,Drazhda,Nish,Baoda,Khvap,Atyr,Frashat,Asha,Push,Barz,Vish,Visa,Aynala,Ornala,Josh,Shkan,Vaem,Mana,Hvoem,Parunam,Taeish,Apana,Kazhna,Puthra,Nmana,Nairi,Xshayath,Adam,Dosta,Bratar,Kichik,Matar,Dala,Danu,Sang,Atar,Ontur,Soltust,Bolk",
  },
  {
    name: "GorirumPersianParthian",
    min: 5,
    max: 14,
    d: "",
    m: 0,
    b: "Gorirum,Anavar,Aivavar,Abiyshan,Hauvar,Andruj,Radavar,Enavar,Hauravar,Omavar,Aivartavar,Haruvaavar,Avarshan,Taishamavar,Ciyavar,Kavar,Adamavar,Yadiyavar,Naiyavar,Tuvamavar,Nekavar,Paravar,Anyavar,Duvaavar,Amahavar,Enahavar,Vayamavar,Griftavar,Budanshan,Namudanshan,Wiyabanshan,Hacaavar,Utashan,Patiyavar,Hamavar,Padavar,Waliavar,Azavar,Hacashan,Yaavar,Xwahavar,Manavavar,Budeavar,Edonavar,Balaavar,Birunavar,Agaravar,Darbareavar,Conavar,Andarvavar,Tanhaavar,Uzavar,Hamconavar,Pasavar,Pasazavar,Karburdanshan,Naxtumavar,Nekiavar,Haravar,Niyazavar,Basavar,Balandavar,Hargizavar,Somalavar,Badavar,Aazanshan,Harduavar,Taavar,Hamiseavar,Agarceavar,Zudavar,Rastavar,Rafanshan,Wadavar,Azansavar,Bartaravar,Andaravar,Artaavar,Suavar,Miyanavar,Hanuzavar,Balartavar,Pusatavar,Ariavar,Puridanshan,Sayadavar,Hastamavar,Xwahidanshan,Besyaravar,Kardanshan,Dastanshan,Oavar,Toavar,Isanavar,Maavar,Guftanshan,Griftanshan,Keavar,Raftanshan,Saxtanshan,Tavanidanshan,Dustdastanshan,Zamanavar,Danistanshan,Salavar,Tavanistavar,Didanshan,Negahidanshan,Amadanshan,Karavar,Rahavar,Nawaavar,Xwastanshan,Dadanshan,Rozavar,Bistaravar,Buzurgavar,Miyanaavar,Buzurgtavar,Dastavar",
  },
  {
    name: "ImperialEngland",
    min: 4,
    max: 9,
    d: "",
    m: 0,
    b: "Imperial,England,Forvel,Hire,Eall,Heora,Hwenne,Eower,Geten,Beon,Seman,Encan,Naht,Butan,Fram,Willen,Wolde,Abutan,Foran,Into,Anolyvel,Ofer,Fter,Brucan,Fyrst,Efne,Neodwyn,Heah,Nfre,Nehst,Beginnan,Begen,Sona,Rihtan,Lfan,Wind,Sian,Ongean,Urhvel,Treowe,Toweard,Sentravel,Stille,Abufan,Behindan,Fyllan,Giet,Ongemang,Mgwyn,Hwer,Sceal,Ghwer,Elles,Cwitevan,Habban,Secgan,Getan,Hwilc,Macian,Cunnan,Gelician,Tima,Iusteval,Witan,Niman,Gear,Geseon,Locian,Cuman,Weorc,Niwe,Wilnian,Gifan,Great,Betweonum,Lytel,Hand,Stede,Healdan,Tyrnan,Feawe,Openian,Togdere,Hwit,Cildru,Wealcan,Bispell,Eaness,Papirvel,Grupavel,Simble,Musicwyn,Mearc,Letravel,Carraft,Caru,Secund,Genog,Planvel,Gyrle,Gewunelic,Geong,Read,Liste,Felan,Talken,Bridd,Bodig,Docga,Familyvel,Posen,Sang,Metan,Duru,Frumwyrc,Scort,Telraft,Clas,Cwestion,Gebyrian",
  },
  {
    name: "KrelnWelshPolynesian",
    min: 4,
    max: 12,
    d: "",
    m: 0,
    b: "Kreln,Seael,Rhianu,Hynnael,Acwael,Amora,Hwnnael,Eidolwi,Hianu,Unael,Poplwi,Acwora,Eiddolwi,Bethael,Pwyal,Mifael,Prydael,Nidael,Ddyolwi,Daolwi,Rhaiol,Arallael,Dwael,Einora,Rhainael,Ninael,Caelodd,Bodanu,Ymddangosddu,Meddylianu,Olwi,Acael,Arael,Gydalwi,Ynael,Ondael,Ganael,Maiora,Neuael,Fyddanu,Fyolwi,Baiddanu,Fellyael,Ianolwi,Allanael,Osael,Amdanael,Oherwylddu,Mewnael,Dimonddu,Drosolwi,Hefydael,Nolael,Wedynael,Defnyddanu,Cyntafael,Dawelwi,Hynddulwi,Unrhywael,Angenael,Ynailwi,Uchelael,Bythddael,Gogleddael,Nesafael,Dechraunu,Ddaulwi,Tanael,Bythael,Erddulwi,Toclwi,Unionolwi,Gaduanu,Gwyntael,Erslwi,Erbynael,Ystodael,Gwirael,Tugiatael,Canoloddael,Ohydael,Uchoddlwi,Tuolael,Ielwi,Llenwanu,Etolwi,Ymlithael,Efallaelu,Wyflwi,Aosael,Rhaidanu,Naill,Eithafael,Gwneuthanu,Caelanu,Efael,Felorael,Tithael,Hwyntael,Dweudanu,Paolwi,Mundanu,Gweuthfanu,Gallanu,Hoffianu,Amserael,Dimondael,Gwybodanu,Cymrydanu,Blwyddael,Gallaidddu,Hwyntlwi,Gweldanu,Edrychanu,Dyfodanu,Deffanu,Gwaithddu,Ffyrddael,Newyddael,Eisiaunu",
  },
  {
    name: "MurrakTasmanian",
    min: 5,
    max: 11,
    d: "",
    m: 0,
    b: "Murrak,Ulara,Rituria,Anlara,Unalara,Italara,Anwal,Tanara,Urana,Manalara,Uiuna,Tanwal,Penalara,Karalara,Minilara,Rillara,Nalara,Zuslara,Rawal,Larilara,Alilara,Zallara,Milara,Itaklara,Turiwal,Svalturia,Anuna,Menturia,Trinturia,Alwal,Iklara,Paralara,Hamlara,Uiwal,Aklara,Eklara,Tilara,Ethnalara,Svanturia,Miwal,Manlara,Uituria,Uralara,Vanalara,Ipalara,Menlara,Unlara,Nangolara,Uzilara,Uzlara,Tulturia,Nawal,Rawauna,Hamwal,Lariwal,Flerturia,Nilwal,Marwal,Urturia,Svallara,Esanlara,Prawlara,Vanturia,Nilalara,Tillara,Hamturia,Rasnawal,Riwal,Menauna,Nallara,Lurlara,Hamuna,Svalwal,Mawal,Manturia,Ipawal,Tanlara,Mithlara,Kapturia,Penlara,Wanaturia,Rawturia,Avillara,Aclnalara,Aclwal,Eturia,Urlara,Wanapara,Nawawal,Turturia,Lannalara,Malara,Suplara,Ezituria,Esanwal,Clanapakana,Peralara,Pakanalara,Lulara,Anklara,Tullara,Achllara,Rulara,Tularwal,Timmenlara,Sulara,Flerlara,Parauna,Secilara,Rawalara,Clanwal,Aiswal,Tezituria,Kanalara,Lautnilara,Luturia,Tularlara,Uruna,Sucwal,Ulawal",
  },
  {
    name: "NaukinMongolianAkkadian",
    min: 4,
    max: 11,
    d: "",
    m: 0,
    b: "Naukin,Tere,Nigen,Anutur,Eneun,Tereun,Anatun,Eneqan,Tereyin,Teremoqan,Nigeun,Qamuqan,Tende,Terenaryin,Yaqun,Kenbul,Biun,Qolunaun,Ugeiun,Tanyin,Sainqan,Jarimun,Ogedeun,Qoyarun,Mananyin,Enenarqan,Bidenun,Olaqanu,Bolanu,Metuqanu,Bodoqanu,Ynun,Baqan,Degerun,Ittibul,Deturqan,Qariunbul,Inatur,Acatur,Esebolun,Bolqanu,Minuyin,Bolquibul,Teyimun,Degedeun,Adaqan,Bolbacun,Toquraqan,Ucirtur,Dotoaun,Jaqunbul,Degerebul,Baqanun,Qariun,Warkitur,Kereglebul,Terigunqan,Sainburqan,Bultaqan,Aliburqan,Keregun,Oluntaqan,Ondurqan,Kolicabul,Umnaqan,Daraqiun,Ekilequnu,Qoyarturqan,Boltalabul,Uridinaun,Bolbacuntur,Turgenbul,Sitiaqan,Arqanu,Salkinun,Acaturaun,Esergebul,Turiqantur,Unenqan,Anuturqan,Dumqitur,Dayunbul,Warkibul,Unenbul,Dugurqanu,Dayuntur,Dotoaturqan,Maadlabul,Bolunbi,Bolquqan,Esebolvul,Ogedeqan,Tumbul,Kiaqanu,Boluqanu,Metubul,Tanun,Terenarqan,Bidenqan,Kelequnu,Aliun,Yabaqanu,Kiabul,Cidaqanu,Durluqanu,Cauntur,Mededequnu,Abaqanu,Jilun,Cidaaqan,Ujequnu,Karaaqanu,Irequnu,Kereglebanu,Uguleqan,Moruntur,Sinequn,Durluturqan,Ogguqanu,Edurun",
  },
  {
    name: "NordalRussian",
    min: 4,
    max: 11,
    d: "",
    m: 0,
    b: "Nordal,Russian,Jedu,Sije,Czto,Kuto,Tvoje,Nase,Namu,Byti,Tamu,Mniti,Mysliti,Aste,Jaze,Tukumo,Takoze,Daze,Sija,Dondze,Skoro,Otunelze,Protivu,Prezde,Jeste,Nadu,Mezdu,Mozebyti,Imatu,Vesima,Tvoriti,Imeti,Resti,Vzeti,Sutvoriti,Mosti,Ljubiti,Vedeti,Videti,Zireti,Prijiti,Upotrebiti,Delati,Oteti,Dati,Durzati,Obrastati,Naceti,Otvrusti,Pecaliti,Cjuti,Glagolati,Testi,Otiti,Ispluniti,Projiti,Dostignati,Pomniti,Slusati,Dvignati,Pasti,Ustvovati,Peti,Poslusati,Vlesti,Sledovati,Javiti,Sluziti,Vladeti,Privladati,Paziti,Plakati,Gnati,Cekati,Vesti,Stati,Sudurzati,Uciti,Razviti,Prinositi,Resiti,Dokazati,Ostati,Prinuditi,Tlaciti,Ispytati,Smejati,Diviti,Proveriti,Obliku,Greti,Prinesti,Krasiti,Plesati,Menjati,Vestati,Osaditi,Loviti,Cistiti,Predstaviti,Sedeti,Verovati,Jaati,Jati,Zeati,Supati,Vzyjiti,Leteti,Raniti,Rezati,Navestiti,Skociti,Skoncati,Nadejti,Oblesti,Rasti,Suresti,Vzti,Razresiti,Variti",
  },
  {
    name: "SolarirumFrench",
    min: 4,
    max: 12,
    d: "",
    m: 0,
    b: "Solarirum,French,Lael,Ivel,Cest,Quei,Vostel,Nostel,Nousel,Estre,Iloel,Sembler,Cuidier,Neiel,Surl,Avequel,Maisiel,Pariel,Devel,Ouvel,Envel,Sivel,Entorel,Cariel,Solemel,Autresi,Apriesel,Mesmeel,Cestel,Josqueel,Tostiel,Desqueel,Encontrel,Enduriel,Versel,Encoriel,Desuriel,Derrieel,Oiel,Entrel,Peutestrel,Deivriel,Ouvelun,Autrel,Asseziel,Faivre,Avoirel,Direiel,Prendre,Calveir,Pouvoirel,Ameir,Savoirel,Prendriel,Veoir,Mirariel,Veniriel,Cuidiel,Useriel,Oevrel,Vouloir,Doneir,Teniriel,Torneir,Aleir,Comenciel,Semblier,Ouvreir,Gardeir,Sentiriel,Parleir,Coureir,Laissieir,Empliriel,Aveneir,Passeir,Ateindrel,Remembreir,Oiriel,Moveir,Cheiriel,Voiajeir,Chanteir,Escoteriel,Tireir,Suivriel,Aparoir,Serviriel,Gouverneir,Reigneir,Noteir,Ploureir,Meneir,Atendrel,Meneiriel,Esteir,Conteneir,Enseigneir,Croistriel,Produireir,Decidieir,Prouveir,Demoreir,Forceir,Boteir,Essaieir,Rireir,Merveillieir,Cerchieir,Formeir,Chaufeir,Aportieir,Peindreir,Danceir,Varieir,Establieir,Chacieir,Conteir,Representeir,Aseeir",
  },
  {
    name: "StoneguardToltec",
    min: 5,
    max: 12,
    d: "",
    m: 0,
    b: "Stoneguard,Tletl,Centli,Yayaru,Yotonal,Nontli,Ipampatli,Initli,Iyaolli,Quenami,Ceyolli,Mochitli,Ompatonal,Innolli,Tleintli,Aquintli,Nechtli,Quenmantli,Ahmolli,Motonal,Quallioshi,Occentli,Occentolli,Ometli,Totonal,Inehtli,Technolli,Quihuiyaru,Yezquyaru,Iximatiyaru,Nemilyaru,Itlatli,Yoantli,Ixpanatli,Ivantli,Icantonal,Yecetli,Ipantli,Ixtli,Anocenolli,Yezquiyaru,Notonal,Mahcenolli,Iuhquintli,Tlacpanolli,Quizayaru,Intlaolli,Ixquicholli,Ipampatonal,Itechtli,Zannolli,Icpactli,Yoantonal,Teyolyaru,Zatepanolli,Tequiyaru,Achtonolli,Qualliyoshi,Yoancetli,Monequitli,Miyaquintli,Ayacnolli,Mictlampatli,Nechcatonal,Pehuayaru,Omentetli,Cemicactli,Macihuitli,Achinolli,Melatonal,Calaquiyaru,Ehecatli,Ixtlamatli,Ixnamicolli,Ipantonal,Nelliolli,Itztiyaru,Tlatlantonal,Ocnolli,Icpactonal,Teputztonal,Quemanolli,Temiiyaru,Nepantlaolli,Yezquibi,Ceminolli,Chihuayaru,Piayaru,Yehtonal,Iuhquintonal,Tehtli,Yehhuantli,Techtonal,Itoayaru,Cuiyaru,Catitli,Yauhyaru,Hueliyaru,Neciyaru,Cahuitli,Yehtli,Matiyaru,Xihuitli,Hueliholli,Yehhuantonal,Ittayaru,Xixittayaru,Huitzayaru,Tequitli,Ohtli,Yancuictli,Nequiyaru,Macayaru,Tonaltli,Cencatli,Hueyolli,Nepantlatli,Hueyotonal,Maitli,Icantli",
  },
  {
    name: "SunbladeGreek",
    min: 4,
    max: 13,
    d: "",
    m: 0,
    b: "Sunblade,Greek,Auto,Touto,Hemon,Hemas,Einai,Ekei,Phainesthai,Noein,Alla,Hypo,Peri,Hoti,Monon,Meta,Tauta,Heos,Takheos,Epei,Kata,Pros,Hyper,Opisthen,Isos,Mellein,Allos,Pantos,Prattein,Ekhein,Legein,Lambanein,Poiein,Dynasthai,Philein,Eidenai,Horan,Blepein,Erkhesthai,Phronein,Khresthai,Ergazesthai,Boulesthai,Didonai,Kratein,Strephein,Badizein,Arkhesthai,Anoigein,Epimelesthai,Aisthesthai,Dialegein,Trekhein,Apienai,Ienai,Pleroun,Gignesthai,Parerkhesthai,Hikanesthai,Mimneskesthai,Akouein,Kinein,Piptein,Hodoiporein,Aeidein,Helkein,Hepesthai,Hypeeretein,Arkhein,Basileuein,Katanoein,Klaien,Elaunein,Menein,Agein,Histanai,Periekhein,Didaskein,Auxanein,Apopherein,Krinein,Apodeiknynai,Anankazein,Othein,Peirazein,Gelan,Thaumazein,Skopein,Morphoun,Thermainein,Pherein,Graphein,Orcheisthai,Alloioun,Agoreuein,Katoikizein,Theran,Arithmein,Eikazein,Kathizein,Pisteuein,Hippazesthai,Eukheisthai,Katheudein,Anabainein,Petesthai,Terein,Temnein,Episkepesthai,Hallesthai,Telein,Elpizein,Amphiennynai,Phyein,Synantan,Airein,Lyein,Hepsein,Kaiein,Apographein",
  },
  {
    name: "SylvarirumNavajo",
    min: 4,
    max: 14,
    d: "",
    m: 0,
    b: "Sylvarirum,Navajo,Haash,Nihi,Holo,Aadi,Yisheeh,Nitsekees,Bikaa,Biih,Doodaii,Gone,Dishniigo,Haala,Altso,Bizhi,Nidi,Diidii,Tsidii,Tsxigo,Bizhiigo,Ndaaz,Biyi,Biighah,Atso,Bikaagi,Bizhidi,Alnahji,Beedahozini,Doolee,Iieeh,Diits,Nayiinih,Alyaa,Hologo,Ayoo,Beehozin,Yiyiinih,Yiilta,Yiists,Naagha,Naanish,Nizhe,Hozho,Yitseed,Naasht,Naaghah,Yilzhod,Yati,Niyol,Yighaah,Iiii,Yitsxiz,Naaznii,Naashnish,Yizhniih,Nahosdzaa,Yistsa,Naazti,Hataa,Yistsago,Yiyii,Yilzhii,Nahatin,Nahata,Yiiltsa,Yicha,Niich,Nizhonigo,Bidiilnish,Sitsooz,Naalzhii,Alyaaigii,Naat,Ahosh,Aojah,Yitsooz,Naalnish,Yidzaaz,Sitso,Nzhoni,Yizhdiilzhaazh,Nizhoni,Nayiisnii,Akee,Beehozingo,Eechaai,Yiyiilnih,Eehsod,Yikaah,Niyolgo,Yizhdii,Yiwod,Atse,Hozhoogo,Push,Ahaa,Yinikaah,Yishjish,Kogo,Yatigo,Naashtizh,Yizhdi,Yikazh,Nahast,Dine,Nitsaa,Awee,Ashkii,Hastiin,Asdzaa,Naataanii,Bilah,Shinaai,Shiyaazh,Shima,Keyah,Tonteel,Naaghahdi,Shadiaah",
  },
  {
    name: "VeildriftSlavicCeltic",
    min: 4,
    max: 13,
    d: "",
    m: 0,
    b: "Veildrift,Tavrath,Jedvrath,Dodru,Onvrath,Onovrath,Zaslav,Ovvrath,Njegovrath,Njenavrath,Onamhar,Jedanvrath,Svimhar,Tamoslav,Njihovrath,Stavrath,Kovrath,Mevrath,Kadvrath,Nevrath,Tvojmhar,Dobarmhar,Nekivrath,Drugvrath,Dvavrath,Nase,Slav,Ovivrath,Nasvrath,Dobivrath,Bitizdru,Cinitimhar,Mislitivrath,Odslav,Ivrath,Navrath,Sazdru,Kodvrath,Alivrath,Prizdru,Odzdru,Ilivrath,Hocedru,Mojslav,Bioslav,Takoslav,Gorezdru,Vanvrath,Akoslav,Ozelj,Jervrath,Uvrath,Samovrath,Prezdru,Takoevrath,Nazadvrath,Poslevrath,Koristidru,Prvimhar,Dobromhar,Cakvrath,Bilokojivrath,Potrebazelj,Cestovrath,Visokslav,Nikadevrath,Severzdru,Sledecivrath,Pocetizdru,Obamhar,Dozdru,Ikadvrath,Madarslav,Uskoslav,Pravomhar,Oticidru,Vetarvrath,Odkadvrath,Protivslav,Tokomvrath,Istinmhar,Premavrath,Sredisnocht,Josvrath,Iznadslav,Izavrath,Davrath,Punizdru,Meunocht,Mozdaslav,Jesmslav,Treba,Veomamhar,Raditizdru,Imatidru,Onslav,Kaomhar,Tivrath,Onivrath,Mizdru,Recizdru,Dobitizdru,Kojivrath,Icizdru,Pravitizdru,Mocidru,Voleti,Vremevrath,Znatizdru,Uzetizdru,Godinazdru,Mogaomhar,Njihvrath,Videtizdru,Gledatizdru,Docizdru,Radzdru,Putslav,Novmhar,Htetizdru",
  },
  {
    name: "VerdathiAboriginal",
    min: 4,
    max: 10,
    d: "",
    m: 0,
    b: "Verdathi,Aboriginal,Ngaa,Yindi,Ngulli,Wunna,Yuurra,Nginda,Coinda,Ngambil,Ngambi,Booroo,Indjal,Woorinda,Mulya,Ulla,Yarra,Wurra,Ngurra,Bimba,Durroo,Djurra,Gundoo,Gaali,Goolba,Warrul,Bulindi,Wullari,Djinba,Yulnga,Ngurroo,Boorindi,Ngullima,Burrandoo,Yandoo,Booranda,Marruwa,Warramba,Gulinda,Burroong,Coola,Indjurra,Wombala,Bulinda,Owwa,Ngarroo,Yulimba,Moolinda,Gooroo,Djirroo,Murroo,Djirrin,Bimbal,Ngulla,Cooba,Wulba,Djirramba,Yurra,Cooinda,Mulunba,Garna,Mirroo,Gurroo,Djulba,Burroo,Ngurloo,Yuramba,Gundja,Marroo,Birroo,Gullaroo,Goomal,Coorinji,Murramba,Djinoon,Ganoo,Booloong,Yindari,Djurroo,Gundara,Mooloong,Guramba,Birrinda,Woomboo,Ganamba,Yurlamba,Burringoo,Ngurrool,Woorinba,Ngamboo,Gundagoo,Mirrooba,Wooroong,Djirramoo,Ngullamba,Djurrimba,Wulamba,Moolooma,Burramba,Djinool,Marramba,Goonoo,Mirroonda,Coorool,Mirroinda,Booramba,Yurramoo,Woorlamba,Yullamba,Djulooba,Coobaloo,Djinamba,Ngullinda,Goora,Ngulamba,Gurnoo,Moogoo,Yurlinga,Yindoo,Wooroo",
  },
  {
    name: "Vethanirum",
    min: 4,
    max: 10,
    d: "",
    m: 0,
    b: "Vethanirum,Loth,Uneth,Aveir,Elho,Aqueth,Pereth,Seuel,Elhorn,Unsol,Toteth,Alaeth,Loreth,Queth,Quieth,Mieth,Quaneth,Noneth,Vostrel,Boneth,Algeth,Nostrel,Aquestel,Noseth,Esseir,Sembleir,Cuideir,Deth,Sobreth,Ambeth,Enneth,Maseth,Devel,Oveth,Veleth,Mieuel,Voldrel,Axieth,Amonteth,Forath,Sieth,Entorel,Careth,Belneth,Solseth,Encareth,Rereeth,Aprethod,Usarel,Primerel,Beneth,Finsel,Qualseveth,Mestereth,Sovineth,Alteth,Jamaisel,Nordeth,Propeth,Comenzeir,Ambdosel,Maiseth,Benquel,Tosteth,Dreteth,Leixeir,Venteth,Dequeth,Contreir,Duraneth,Verael,Enversel,Centreil,Oileth,Empleir,Entremeth,Potserel,Sothel,Caldreth,Altreil,Forceth,Fereir,Avereir,Elhel,Cometh,Voseth,Elhosel,Direir,Prendreir,Qualth,Anareir,Podereir,Amareth,Tempsel,Elheth,Sabereir,Preneir,Aneth,Poguereth,Elhoseth,Veureir,Gardeir,Venireir,Usareir,Laboreth,Camineth,Noveth,Volereth,Doneir,Diaeth,Masel,Graneth,Entrel,Maneth,Loceth,Tenireir,Girareir,Poceth,Obrireir,Ensembleth",
  },
];

